# -*- coding: utf-8 -*-
"""Trab1_Artur_Mendes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rtuqYOmA8FqlMUgJNtHzvavOYdUZ2o38
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import GridSearchCV, cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.base import clone
from collections import Counter
from scipy import stats
from sklearn.base import BaseEstimator, ClassifierMixin

"""#Carregando o dataset"""

!wget -O jogos.csv 'https://drive.google.com/uc?export=download&id=1vWz_B1ZyGTEaXRfeyxGmt8W9Hg6R8gb8'

df = pd.read_csv('jogos.csv')

# print(df.to_string())

"""#Pré-processamento

Aqui filtrarei apenas as colunas que vou utilizar, no meu caso as colunas de dados aos 10 minutos e pré-jogo
"""

colunas_desejadas = ['result', 'golddiffat10', 'xpdiffat10', 'csdiffat10', 'killsdiffat10', 'assistsdiffat10', 'WR', 'KD', 'GPR', 'GSPD', 'EGR',
        'MLR', 'FB%', 'FT%', 'F3T%', 'HLD%', 'DRG%', 'BN%', 'LNE%', 'JNG%', 'OPP_WR', 'OPP_KD', 'OPP_GPR', 'OPP_GSPD',
        'OPP_EGR', 'OPP_MLR', 'OPP_FB%', 'OPP_FT%', 'OPP_F3T%', 'OPP_HLD%', 'OPP_DRG%', 'OPP_BN%', 'OPP_LNE%', 'OPP_JNG%']
df = df[colunas_desejadas]

print(df)

df.head()

#Convertendo os valores das colunas de string para numerico
df['result'] = pd.to_numeric(df['result'], downcast='integer', errors='coerce')
for col in df:
  if col != 'result':
    df[col] = pd.to_numeric(df[col], downcast='float', errors='coerce')

print(df)

"""Aqui analisarei se existe algum valor nulo na base de dados para, se necessário, filtrar os dados. E também analisarei algumas métricas importantes como média, desvio padrão (que são usados para padronização)"""

print(df.isnull().sum())
print(df.describe(include='all'))

"""##Usando os classificadores

Separando os dados do target (result).
"""

df_x = df.drop('result', axis=1)
df_y = df['result']

def classification_report(scores):
    print(f'Media: {scores.mean():.2f}, Desvio Padrao: {scores.std():.2f}')
    inf, sup = stats.norm.interval(0.95, loc=scores.mean(),
                               scale=scores.std()/np.sqrt(len(scores)))
    print(f'Intervalo de confiança (95%): [{inf:.2f},{sup:.2f}]')

scalar = StandardScaler()

rkf = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=36854321)

modelos = [
    ("DT", DecisionTreeClassifier(random_state=13), {
      'estimator__criterion': ['gini','entropy'],
      'estimator__max_depth': [5, 10, 15, 25]
    }),

    ("KNN", KNeighborsClassifier(), {
      'estimator__n_neighbors':[1,3,5,7,9]
    }),

    # Coloquei o early_stopping=True pois o MLP estava demorando muito para completar (mais de 3 horas e nada de resultados)
    # Tirei dúvida em relação ao early_stopping e foi autorizado
    ("MLP", MLPClassifier(random_state=13, early_stopping=True), {
      'estimator__hidden_layer_sizes': [(100,),(10,)],
      'estimator__alpha': [0.0001, 0.005],
      'estimator__learning_rate': ['constant','adaptive']
    }),

    ("RF", RandomForestClassifier(random_state=13), {
      'estimator__n_estimators': [5, 10, 15, 25],
      'estimator__max_depth': [10, None]
    }),
]

resultados = {}

for nome, modelo, grade in modelos:
  print(f"\nModelo: {nome}")
  pipeline = Pipeline([('transformer', scalar), ('estimator', modelo)])

  gs = GridSearchCV(estimator=pipeline, param_grid=grade, n_jobs=-1, cv=4)
  scores = cross_val_score(gs, df_x, df_y, cv=rkf)

  print("Scores:", scores)
  print("Média de acurácia:", scores.mean())
  classification_report(scores)
  resultados[nome] = scores

linhas = []

for nome, scores in resultados.items():
    media = scores.mean()
    desvio = scores.std()
    inf, sup = stats.norm.interval(0.95, loc=scores.mean(),
                               scale=scores.std()/np.sqrt(len(scores)))
    linhas.append([nome, media, desvio, inf, sup])

tabela = pd.DataFrame(linhas, columns=["Método", "Média", "Desvio Padrão", "Limite Inferior", "Limite Superior"])
print("\nTabela de Resultados:")
print(tabela.round(2))

def t_corrigido_nadeau_bengio(data1, data2, X, n_folds_externos):
    """
    Parâmetros:
        data1, data2: listas ou arrays com as acurácias
        X: conjunto de dados original
        n_folds_externos: número de folds no loop externo
    Retorna:
        t_stat: valor da estatística t
        p_valor: valor-p do teste bilateral
    """
    N = len(X)  # número total de amostras no dataset
    n = len(data1)  # número de execuções
    # Tamanhos dos conjuntos de treino/teste em cada fold externo
    n_test = N // n_folds_externos
    n_train = N - n_test
    # Cálculo da estatística t com correção
    diffs = np.array(data1) - np.array(data2)
    mean_diff = np.mean(diffs)
    std_diff = np.std(diffs, ddof=1)
    se_corrigido = std_diff * np.sqrt(1/n + n_test/n_train)
    t_stat = mean_diff / se_corrigido
    p_valor = 2 * (1 - stats.t.cdf(abs(t_stat), df=n - 1))
    return t_stat, p_valor

print('\nCorrected T Test')
s,p = t_corrigido_nadeau_bengio(resultados["MLP"],resultados["RF"],df,10)
print("t: %0.2f p-value: %0.2f\n" % (s,p))

def states_total_value(states):
    total_sum = 0
    for state in states:
        total_sum = total_sum + state[0]
    return total_sum

def roulette_construction(states):
    aux_states = []
    roulette = []
    total_value = states_total_value(states)

    for state in states:
        value = state[0]
        if total_value != 0:
            ratio = value/total_value
        else:
            ratio = 1
        aux_states.append((ratio,state[1]))

    acc_value = 0
    for state in aux_states:
        acc_value = acc_value + state[0]
        s = (acc_value,state[1])
        roulette.append(s)
    return roulette

roulette_construction([(1, [1,0,0]), (4, [0, 1, 0]), (5, [0, 0, 1])])

import random

def roulette_run (rounds, roulette):
    if roulette == []:
        return []
    selected = []
    while len(selected) < rounds:
        r = random.uniform(0,1)
        for state in roulette:
            if r <= state[0]:
                selected.append(state[1])
                break
    return selected

roulette_run (1, [(0.1, [1, 0, 0]), (0.5, [0, 1, 0]), (1.0, [0, 0, 1])])

class HeterogeneousBoosting(BaseEstimator, ClassifierMixin): #Herda de BaseEstimator e ClassifierMixin para poder ser usado em cross_val_score
    def __init__(self, n_estimators=50):
        self.n_estimators = n_estimators

    def fit(self, X, y):
        self.classe_mais_frequente = y.mode()[0]
        X = np.array(X)
        y = np.array(y)
        self.models = []


        pesos = np.ones(len(X))

        classificadores_base = [
            ("MLP", MLPClassifier(early_stopping=True, random_state=13)),
            ("DT", DecisionTreeClassifier(random_state=13)),
            ("KNN", KNeighborsClassifier()),
            ("GNB", GaussianNB())
        ]

        for i in range(self.n_estimators):
            states = list(zip(pesos, range(len(X)))) #Cria uma lista de tuplas peso, index
            roleta = roulette_construction(states)
            idx_selecionado = roulette_run(len(X), roleta) #Seleciona os conjuntos com base no algoritmo da roleta
            X_sample = X[idx_selecionado]
            y_sample = y[idx_selecionado]

            melhor_score = -1
            melhor_modelo = None
            nome_melhor_modelo = None
            for nome, classificador in classificadores_base: #Para cada um dos métodos de classificação treina, testa
                modelo = classificador.__class__(**classificador.get_params())
                modelo.fit(X_sample, y_sample)
                previsoes = modelo.predict(X_sample)
                acuracia = (previsoes == y_sample).mean()
                if acuracia > melhor_score or (acuracia == melhor_score and self._prefer(nome, nome_melhor_modelo)): #Salva o modelo como melhor caso ele seja o melhor até o momento
                    melhor_score = acuracia
                    melhor_modelo = modelo
                    nome_melhor_modelo = nome

            self.models.append(melhor_modelo) #Adiciona na lista de modelos incorporados

            previsoes = melhor_modelo.predict(X_sample) #Dobra o peso dos exemplos classificados de forma errônea pelo melhor classificador
            for i, idx in enumerate(idx_selecionado):
                if previsoes[i] != y_sample[i]:
                    pesos[idx] *= 2

        return self

    def predict(self, X):
        previsoes = []
        for x in X:
            votos = [modelo.predict([x])[0] for modelo in self.models] #Para todos os modelos incorporados obtém classificação e armazena as classes selecionadas
            contagem = Counter(votos)
            max_voto = contagem.most_common(1)[0][1]
            empatadas = [classe for classe, voto in contagem.items() if voto == max_voto]
            if len(empatadas) == 1:
                previsoes.append(empatadas[0])
            else:
                if self.classe_mais_frequente in empatadas:
                    previsoes.append(self.classe_mais_frequente) #Retorna a classe mais frequente caso empate
                else:
                    previsoes.append(empatadas[0])
        return np.array(previsoes) #Retorna a classe mais votada

    def _prefer(self, novo, atual): #Chaves de Preferência
        ordem = {"MLP": 0, "DT": 1, "KNN": 2, "GNB": 3}
        return atual is None or ordem[novo] < ordem[atual]

scalar = StandardScaler()
rkf = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=36854321)

# Adiciona o HeterogeneousBoosting à sua lista de modelos
modelos = [(
    "HB",
    HeterogeneousBoosting(),
    {'estimator__n_estimators': [5, 10, 15, 25, 50]}
)]

# Treinando todos os modelos (incluindo agora o HB)
for nome, modelo, grade in modelos:
    print(f"\nModelo: {nome}")
    pipeline = Pipeline([('transformer', scalar), ('estimator', modelo)])
    gs = GridSearchCV(estimator=pipeline, param_grid=grade, n_jobs=-1, cv=4)
    scores = cross_val_score(gs, df_x, df_y, cv=rkf)

    print("Scores:", scores)
    print("Média de acurácia:", scores.mean())
    classification_report(scores)
    resultados[nome] = scores

plt.boxplot([resultados['DT'],resultados['KNN'],resultados['MLP'], resultados['RF']])

plt.xticks([1,2,3,4],['Decision Tree','KNN','Multilayer-Perceptron', 'Random-Forest'])
plt.xlabel("Classifiers")
plt.ylabel("Média")
plt.title("Classifiers Comparision Boxplot")
plt.show()

scores_dict = {
    'DT': resultados["DT"],
    'KNN': resultados["KNN"],
    'MLP': resultados["MLP"],
    'RF': resultados["RF"],
}

modelos = list(scores_dict.keys()) #Transformando em lista para poder acessar os resultados por i e j
n = len(modelos)
matriz = [["" for _ in range(n)] for _ in range(n)]

for i in range(n):
    for j in range(n):
        if i == j:
            matriz[i][j] = modelos[i]
        elif i < j:
            t, p_t = t_corrigido_nadeau_bengio(
                scores_dict[modelos[i]],
                scores_dict[modelos[j]],
                df_x,
                n_folds_externos=10
            )
            p_t = p_t.round(3)
            if p_t <= 0.05:
              valor = f"*{p_t}*"
            else:
              valor = p_t
            matriz[i][j] = valor
        elif i > j:
            t, p_w = stats.wilcoxon(
                scores_dict[modelos[i]],
                scores_dict[modelos[j]]
            )
            p_w = p_w.round(3)
            if p_w <= 0.05:
              valor = f"*{p_w}*"
            else:
              valor = p_w
            matriz[i][j] = valor

# Criando DataFrame com pandas
tabela = pd.DataFrame(matriz)

# Exibir tabela formatada
print("Tabela pareada de p-values:")
print(tabela)